### ISSUE TITLE
can't run examples

### ISSUE THREAD

**Issue by taylorwc** [Pillar1989/AWS_SDK_for_BBG#1]
I've been following instructions on this, thanks for posting! 

Currently having issues with getting an example running. Trying Helloworld.js. When I attempt to run, this is the error thrown on the console:

```javascript
crypto.js:100
      c.context.setKey(options.key);
                ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:100:17)
    at Object.exports.connect (tls.js:1329:27)
    at Object.buildBuilder (/var/lib/cloud9/node_modules/mqtt/lib/connect/tls.js:11:20)
    at MqttClient.wrapper [as streamBuilder] (/var/lib/cloud9/node_modules/mqtt/lib/connect/index.js:128:36)
    at MqttClient._setupStream (/var/lib/cloud9/node_modules/mqtt/lib/client.js:209:22)
    at new MqttClient (/var/lib/cloud9/node_modules/mqtt/lib/client.js:190:8)
    at Object.connect (/var/lib/cloud9/node_modules/mqtt/lib/connect/index.js:131:10)
    at aws_iot.connect (/var/lib/cloud9/AWS_SDK_for_BBG/src/aws_iot.js:80:22)
    at Object.<anonymous> (/var/lib/cloud9/AWS_SDK_for_BBG/example/Helloworld.js:13:12)
    at Module._compile (module.js:456:26)
```

I have triple checked my certificates and file paths and still no luck. Do you have any tips? Thanks in advance.

**Comment by Pillar1989** [comment]
Please make sure : 
root:prodCerts#mv a3a39a19de-private.pem.key device_key.pem
root:prodCerts#mv a3a39a19de-certificate.pem.crt.txt device_identity.pem
root:prodCerts#cd ../
root:IotSdkJS#cd example/
root:example#node Helloworld.js 
and VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem download from https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem

I have been made a test. If I rename xxxxx-private.pem.key as device_identity.pem and rename a3a39a19de-certificate.pem.crt.txt as  device_key.pem. It  print same error like yours.

**Comment by taylorwc** [comment]
How embarrassing--I did have them backwards! That did it, thanks for the help.
